### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [deusxmach1na/MapleJuice#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. It seems like a great project to learn from. Thank you.

**Comment by deusxmach1na** [comment]
Hey, this is a project for my CS425 class from University of Illinois class I took.  This is basically my implementation of MapReduce.  You might wanna look at my implementation of a Distributed File System too since they were meant to work hand in hand.  https://github.com/deusxmach1na/DistributedFileSystem. 

There is no license, feel free to copy it or change it however you like.  I am not responsible for any damage it causes though :)

Also, I only ever tested it on one local machine using different ports, not on a bunch of machines.

**Comment by suprafun** [comment]
Thank you so very much. Would it be possible for you to please upload a formal license to the repo. ( e.g. MIT, GPL, BSD, whatever you prefer). I ask so I can be sure of how I should treat this project. Other people (like learners like myself) might benefit from it. Thank you.

**Comment by deusxmach1na** [comment]
Done, good luck.  I think I have the DistributedFileSystem code in here too actually.  So you just need to study this repo to understand how HDFS works, gossip protocol (keeps a list of other machines and updates over UDP), and MapReduce (MapleJuice).
